<?php
    /**
     * Created by PhpStorm.
     * User: marco
     * Date: 12/07/16
     * Time: 11:31
     */

    namespace Microsistec\DbParser\Parser\Old;


    use Microsistec\DbParser\Definition\MassAssignmentable;

    class SeasonParser extends RentParser
    {
        public function parse($model, MassAssignmentable $massAssignmentable, $object = null)
        {
            $season = new \Microsistec\DbParser\Definition\Disponibility\Season;

            $season = parent::parse($model, $massAssignmentable, $season ); // TODO: Change the autogenerated stub

            $season->highSeason = $model->valor_locacao_alta_temporada;
            $season->lowSeason = $model->valor_locacao_baixa_temporada;

            return $season;
        }

    }