<?php
/**
 * Created by PhpStorm.
 * User: unm
 * Date: 30/03/2017
 * Time: 19:05
 */

namespace Microsistec\DbParser\Parser\Desktop\PropertyTypes\Characteristics\Transformers;


class PatternTransformer  extends PositionTransformer
{
    public function transform($values, $base, $defaults, $options = [])
    {
        $fields = [];
        $possibilities = count($base);

        foreach ($options as $key => $field) {
            $toSkip = $key * $possibilities;

            if ($key > 0) {
                $toSkip += 1;
            }

            $slice = substr($values,$toSkip , $possibilities);

            $fields[$field] = parent::transform($slice, $base, $defaults, []);
        }

        return $fields; // TODO: Change the autogenerated stub
    }


}